---
- name: Download k3s installation script
  get_url: 
    url: "{{ script_url }}"
    dest: "./roles/{{ role_name }}/files/{{ script_name }}"
    mode: 0700
  delegate_to: localhost

- name: Install k3s
  script: "{{ script_name }}"
  args:
    creates: /usr/local/bin/k3s

- name: Remove installation script
  file:
    path: "./roles/{{ role_name }}/files/{{ script_name }}"
    state: absent
  delegate_to: localhost