- name: Install required packages (this may take a while)
  package:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: yes
  with_items: 
    - "{{ virtualization_packages }}"
    - "{{ iso_packages }}"

- name: Enable libvirt daemon
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: Add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes